names = "usama,alyan"
len1 = len(names)
print(len1)
#Length using index 
print(names[0:1])
print(names[0:2])
print(names[0:3])
print(names[0:4])
print(names[0:5])
print(names[0:6])
print(names[0:7])
print(names[0:8])
print(names[0:9])
print(names[0:10])
print(names[0:11])
print(names[0:12])
print(names[0:11])
print(names[0:10])
print(names[0:9])
print(names[0:8])
print(names[0:7])
print(names[0:6])
print(names[0:5])
print(names[0:4])
print(names[0:3])
print(names[0:2])
print(names[0:1])
# print(names[:])
# print(names[2:6])
# print(names[3:6])
# print(names[4:6])
# #-8 cancels the last 8 words of string 
# print(names[0:-11])
# print(names[0:-10])
# print(names[0:-9])
# print(names[0:-7])
# print(names[0:-6])
# print(names[0:-5])
# print(names[0:-4])
# print(names[0:-3])
# print(names[0:-2])
# print(names[-4:-2])
# num = 1,2,3,4,5,6
# for i in num:
#  print(i) 

